# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abc332548c37bf10e968772e91d2a65a985c151596359c00e899f48f447f71384a74c528721ee6179fa252bc9fa1883cfe194a5214353764374e643b313887a8

test:
  secret_key_base: 0e1363fb9448e1f6f904eaa875f906d2da9a01f5b996990032b339216e7354cf1991b4c80b084087abb8cd14ebac88e5ee5df3ebb9bbd9e7414cc1e10d0cb308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
